### ISSUE TITLE
公章生成的法律建议

### ISSUE THREAD

**Issue by Catherina0** [31core/prescription#1]
伪造公司、企业、事业单位、人民团体印章罪：
根据《刑法》第280条第二款，伪造公司、企业、事业单位、人民团体的印章，处三年以下有期徒刑、拘役、管制或者剥夺政治权利；情节严重的，处三年以上十年以下有期徒刑。

使用虚假公司印章罪：
根据《刑法》第280条第三款，使用伪造的公司、企业、事业单位、人民团体的印章的，依照前款的规定处罚。

伪造、变造、买卖公文、证件、证明文件、印章的行为：
根据《治安管理处罚法》第52条，伪造、变造、买卖公文、证件、证明文件、印章的，处10日以上15日以下拘留，可以并处一千元以上五千元以下罚款；情节较轻的，处5日以上10日以下拘留，可以并处五百元以上一千元以下罚款。

故不建议增加公章生成

**Comment by 31core** [comment]
如果是虚构一个组织制作公章算是伪造公章吗？ 或许可以在程序启动时增加一个需确认的使用条款, `“我确认公章所指明的单位在现实中不存在, 并且不会影响他人的合法权益”`, 就例如很多在线公章生成器都会有类似的免责声明
![Screenshot from 2024-07-04 22-00-06](https://github.com/31core/prescription/assets/49990217/8d9dc298-9cd1-4d8d-a2e9-1c9ecd4de780)

**Comment by Catherina0** [comment]
伪造文书罪：根据《中华人民共和国刑法》第二百四十四条规定，伪造、变造、买卖国家机关公文、证件、印章等重要文书，情节严重的，处三年以下有期徒刑或者拘役，并处或者单处罚金；情节特别严重的，处三年以上七年以下有期徒刑，并处罚金。

医院是可以作为伪造文书罪的主体的（）  严格意义上你加上公章就算伪造文书

**Comment by 31core** [comment]
那我下次提交顺便把README改了

**Comment by 31core** [comment]
谢谢提醒
